struct MockData {
    static func getPlannedTripsmock() -> [PlannedTrip] {
        return [
            PlannedTrip(id: 1, destination: "Paris Road Trip", startDate: "19th April, 2024", durationDays: 5),
            PlannedTrip(id: 2, destination: "New York Family Trip", startDate: "19th April, 2024", durationDays: 10),
            PlannedTrip(id: 3, destination: "Paris Work Trip", startDate: "19th April, 2024", durationDays: 5),
            PlannedTrip(id: 4, destination: "New York Anniversary", startDate: "19th April, 2024", durationDays: 10),
            PlannedTrip(id: 5, destination: "Paris Fashion Show", startDate: "19th April, 2024", durationDays: 5),
            PlannedTrip(id: 6, destination: "New York Movie Awards", startDate: "19th April, 2024", durationDays: 10),
        ]
    }
}

let airportsData: [AirportCity] = [
    AirportCity(cityName: "Atlanta", airportName: "Hartsfield–Jackson Atlanta International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Beijing", airportName: "Beijing Capital International Airport", countryName: "China", countryCode: "CN"),
    AirportCity(cityName: "Dubai", airportName: "Dubai International Airport", countryName: "United Arab Emirates", countryCode: "AE"),
    AirportCity(cityName: "Los Angeles", airportName: "Los Angeles International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Tokyo", airportName: "Haneda Airport", countryName: "Japan", countryCode: "JP"),
    AirportCity(cityName: "Chicago", airportName: "O'Hare International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "London", airportName: "Heathrow Airport", countryName: "United Kingdom", countryCode: "GB"),
    AirportCity(cityName: "Hong Kong", airportName: "Hong Kong International Airport", countryName: "Hong Kong", countryCode: "HK"),
    AirportCity(cityName: "Shanghai", airportName: "Shanghai Pudong International Airport", countryName: "China", countryCode: "CN"),
    AirportCity(cityName: "Paris", airportName: "Charles de Gaulle Airport", countryName: "France", countryCode: "FR"),
    AirportCity(cityName: "Dallas/Fort Worth", airportName: "Dallas/Fort Worth International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Guangzhou", airportName: "Guangzhou Baiyun International Airport", countryName: "China", countryCode: "CN"),
    AirportCity(cityName: "Frankfurt", airportName: "Frankfurt am Main Airport", countryName: "Germany", countryCode: "DE"),
    AirportCity(cityName: "Istanbul", airportName: "Istanbul Airport", countryName: "Turkey", countryCode: "TR"),
    AirportCity(cityName: "Delhi", airportName: "Indira Gandhi International Airport", countryName: "India", countryCode: "IN"),
    AirportCity(cityName: "Jakarta", airportName: "Soekarno–Hatta International Airport", countryName: "Indonesia", countryCode: "ID"),
    AirportCity(cityName: "Singapore", airportName: "Changi Airport", countryName: "Singapore", countryCode: "SG"),
    AirportCity(cityName: "Seoul", airportName: "Incheon International Airport", countryName: "South Korea", countryCode: "KR"),
    AirportCity(cityName: "Bangkok", airportName: "Suvarnabhumi Airport", countryName: "Thailand", countryCode: "TH"),
    AirportCity(cityName: "Madrid", airportName: "Adolfo Suárez Madrid–Barajas Airport", countryName: "Spain", countryCode: "ES"),
    AirportCity(cityName: "New York City", airportName: "John F. Kennedy International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "San Francisco", airportName: "San Francisco International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Barcelona", airportName: "Barcelona–El Prat Airport", countryName: "Spain", countryCode: "ES"),
    AirportCity(cityName: "Munich", airportName: "Munich Airport", countryName: "Germany", countryCode: "DE"),
    AirportCity(cityName: "Miami", airportName: "Miami International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Rome", airportName: "Leonardo da Vinci–Fiumicino Airport", countryName: "Italy", countryCode: "IT"),
    AirportCity(cityName: "Doha", airportName: "Hamad International Airport", countryName: "Qatar", countryCode: "QA"),
    AirportCity(cityName: "Amsterdam", airportName: "Amsterdam Airport Schiphol", countryName: "Netherlands", countryCode: "NL"),
    AirportCity(cityName: "Kuala Lumpur", airportName: "Kuala Lumpur International Airport", countryName: "Malaysia", countryCode: "MY"),
    AirportCity(cityName: "Toronto", airportName: "Toronto Pearson International Airport", countryName: "Canada", countryCode: "CA"),
    AirportCity(cityName: "Houston", airportName: "George Bush Intercontinental Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Shenzhen", airportName: "Shenzhen Bao'an International Airport", countryName: "China", countryCode: "CN"),
    AirportCity(cityName: "Chengdu", airportName: "Chengdu Shuangliu International Airport", countryName: "China", countryCode: "CN"),
    AirportCity(cityName: "Mexico City", airportName: "Mexico City International Airport", countryName: "Mexico", countryCode: "MX"),
    AirportCity(cityName: "Melbourne", airportName: "Melbourne Airport", countryName: "Australia", countryCode: "AU"),
    AirportCity(cityName: "São Paulo", airportName: "São Paulo/Guarulhos International Airport", countryName: "Brazil", countryCode: "BR"),
    AirportCity(cityName: "Bogotá", airportName: "El Dorado International Airport", countryName: "Colombia", countryCode: "CO"),
    AirportCity(cityName: "Johannesburg", airportName: "O. R. Tambo International Airport", countryName: "South Africa", countryCode: "ZA"),
    AirportCity(cityName: "Vienna", airportName: "Vienna International Airport", countryName: "Austria", countryCode: "AT"),
    AirportCity(cityName: "Zurich", airportName: "Zurich Airport", countryName: "Switzerland", countryCode: "CH"),
    AirportCity(cityName: "Istanbul", airportName: "Sabiha Gökçen International Airport", countryName: "Turkey", countryCode: "TR"),
    AirportCity(cityName: "Boston", airportName: "Logan International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Washington, D.C.", airportName: "Dulles International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Seattle", airportName: "Seattle–Tacoma International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Philadelphia", airportName: "Philadelphia International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Dallas", airportName: "Love Field", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Copenhagen", airportName: "Copenhagen Airport", countryName: "Denmark", countryCode: "DK"),
    AirportCity(cityName: "Oslo", airportName: "Oslo Airport, Gardermoen", countryName: "Norway", countryCode: "NO"),
    AirportCity(cityName: "Stockholm", airportName: "Stockholm Arlanda Airport", countryName: "Sweden", countryCode: "SE"),
    AirportCity(cityName: "Helsinki", airportName: "Helsinki-Vantaa Airport", countryName: "Finland", countryCode: "FI"),
    AirportCity(cityName: "Brussels", airportName: "Brussels Airport", countryName: "Belgium", countryCode: "BE"),
    AirportCity(cityName: "Lisbon", airportName: "Humberto Delgado Airport", countryName: "Portugal", countryCode: "PT"),
    AirportCity(cityName: "Athens", airportName: "Athens International Airport", countryName: "Greece", countryCode: "GR"),
    AirportCity(cityName: "Manila", airportName: "Ninoy Aquino International Airport", countryName: "Philippines", countryCode: "PH"),
    AirportCity(cityName: "Taipei", airportName: "Taiwan Taoyuan International Airport", countryName: "Taiwan", countryCode: "TW"),
    AirportCity(cityName: "Mumbai", airportName: "Chhatrapati Shivaji Maharaj International Airport", countryName: "India", countryCode: "IN"),
    AirportCity(cityName: "Chennai", airportName: "Chennai International Airport", countryName: "India", countryCode: "IN"),
    AirportCity(cityName: "Bangalore", airportName: "Kempegowda International Airport", countryName: "India", countryCode: "IN"),
    AirportCity(cityName: "Hyderabad", airportName: "Rajiv Gandhi International Airport", countryName: "India", countryCode: "IN"),
    AirportCity(cityName: "Cairo", airportName: "Cairo International Airport", countryName: "Egypt", countryCode: "EG"),
    AirportCity(cityName: "Cape Town", airportName: "Cape Town International Airport", countryName: "South Africa", countryCode: "ZA"),
    AirportCity(cityName: "Lagos", airportName: "Murtala Muhammed International Airport", countryName: "Nigeria", countryCode: "NG"),
    AirportCity(cityName: "Casablanca", airportName: "Mohammed V International Airport", countryName: "Morocco", countryCode: "MA"),
    AirportCity(cityName: "Doha", airportName: "Doha Hamad International Airport", countryName: "Qatar", countryCode: "QA"),
    AirportCity(cityName: "Abu Dhabi", airportName: "Abu Dhabi International Airport", countryName: "United Arab Emirates", countryCode: "AE"),
    AirportCity(cityName: "Riyadh", airportName: "King Khalid International Airport", countryName: "Saudi Arabia", countryCode: "SA"),
    AirportCity(cityName: "Jeddah", airportName: "King Abdulaziz International Airport", countryName: "Saudi Arabia", countryCode: "SA"),
    AirportCity(cityName: "Doha", airportName: "Hamad International Airport", countryName: "Qatar", countryCode: "QA"),
    AirportCity(cityName: "Tehran", airportName: "Imam Khomeini International Airport", countryName: "Iran", countryCode: "IR"),
    AirportCity(cityName: "Karachi", airportName: "Jinnah International Airport", countryName: "Pakistan", countryCode: "PK"),
    AirportCity(cityName: "Lima", airportName: "Jorge Chávez International Airport", countryName: "Peru", countryCode: "PE"),
    AirportCity(cityName: "Santiago", airportName: "Comodoro Arturo Merino Benítez International Airport", countryName: "Chile", countryCode: "CL"),
    AirportCity(cityName: "Buenos Aires", airportName: "Ministro Pistarini International Airport", countryName: "Argentina", countryCode: "AR"),
    AirportCity(cityName: "Auckland", airportName: "Auckland Airport", countryName: "New Zealand", countryCode: "NZ"),
    AirportCity(cityName: "Perth", airportName: "Perth Airport", countryName: "Australia", countryCode: "AU"),
    AirportCity(cityName: "Brisbane", airportName: "Brisbane Airport", countryName: "Australia", countryCode: "AU"),
    AirportCity(cityName: "Doha", airportName: "Hamad International Airport", countryName: "Qatar", countryCode: "QA"),
    AirportCity(cityName: "Montreal", airportName: "Montréal–Trudeau International Airport", countryName: "Canada", countryCode: "CA"),
    AirportCity(cityName: "Vancouver", airportName: "Vancouver International Airport", countryName: "Canada", countryCode: "CA"),
    AirportCity(cityName: "Edmonton", airportName: "Edmonton International Airport", countryName: "Canada", countryCode: "CA"),
    AirportCity(cityName: "Calgary", airportName: "Calgary International Airport", countryName: "Canada", countryCode: "CA"),
    AirportCity(cityName: "Honolulu", airportName: "Daniel K. Inouye International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Las Vegas", airportName: "Harry Reid International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Orlando", airportName: "Orlando International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Denver", airportName: "Denver International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Phoenix", airportName: "Phoenix Sky Harbor International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Detroit", airportName: "Detroit Metropolitan Wayne County Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Minneapolis", airportName: "Minneapolis–Saint Paul International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Charlotte", airportName: "Charlotte Douglas International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "San Diego", airportName: "San Diego International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Portland", airportName: "Portland International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Salt Lake City", airportName: "Salt Lake City International Airport", countryName: "United States", countryCode: "US"),
    AirportCity(cityName: "Anchorage", airportName: "Ted Stevens Anchorage International Airport", countryName: "United States", countryCode: "US")
]

